### PR TITLE
Localisation

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
@bboulesteix, do you think you would be able to help me translate [this view](https://github.com/entrepreneur-interet-general/bulletins/blob/master/resources/views/about.blade.php)? This is the only major thing to translate.

**Comment by bboulesteix** [comment]
> @bboulesteix, do you think you would be able to help me translate [this view](https://github.com/entrepreneur-interet-general/bulletins/blob/master/resources/views/about.blade.php)? This is the only major thing to translate.

Sure. Will do.

**Comment by bboulesteix** [comment]
Here's what you asked for:

```html
@extends('master')

@section('content')
<div class="dark-background" style="max-width: 750px; margin: 0 auto">
  <h1>About this tool</h1>
  <p class="lead-text">This tool is an asynchronous alternative to stand-up meetings—also called status meetings, or updates.</p>

  <h2>What this tool does</h2>
  <p>
    During stand-up meetings, some coworkers come together at the same time, in the same place, and they speak one at a time about what's going on. In other words, stand-up meetings require several people to stop what they're doing so that everybody can hear the exact same thing at the exact same time. The problem is: some things can wait. The kind of things shared during status meetings can usually wait a few hours for people to be ready to absorb it.
  </p>
  <p>
    So instead of pulling people away from from their work at the exact same time, this tool allows each team to write up a weekly statut report on their own schedule. Status repots are posted to a form so that each team can write it up whenever they're ready. When every team has posted its status report, the reports are aggregated into a newsletter that is sent to all the teams. Just like a status meeting would do, but without breaking people's productivity.
  </p>
  
  <h2>How this tool works</h2>
  <ol>
    <li>Each teams fills out its weekly status report using a dedicated form ;</li>
    <li>Status reports are aggregated and turned into a newsletter sent every Friday at 3PM.</li>
  </ol>

  <h2>How reports are shared</h2>
  <p>
    Although this tool's code is open source, status reports posted to it are not public. That being said, status reports are written up to be shared with some people. Therefore, this tool acts as a permanent home for your team's status report, which allow you to:
    <ul>
    <li>get access to all the reports posted by your team.</li>
    <li>create a link for your report and share it with external readers.</li>
    <li>export your reports.</li>
  </p>

  <h2>Weekly deadlines</h2>
  <p>
    Keep in mind the following deadlines:
    <ul>
      <li>Every Monday morning: the form for the current week opens.</li>
      <li>Every Friday at 3:00 PM: the form for the current week closes.</li>
      <li>Every Friday at 3:05 PM: the weekly newsletter is sent to teams.</li>
    </ul>
  </p>
</div>

@endsection
```

**Comment by AntoineAugusti** [comment]
@bboulesteix Thanks a lot Brice! 🙏 I found a way to coauthor commits to credit you 😉

**Pull request merged**
