### PR TITLE
feat: add docker-compose setup

### PR DESCRIPTION
**Pull request by revolunet**
Add a docker-compose setup for dev and/or production.

the *.conf files can be moved to a docker folder if you prefer

### CODE REVIEW

**Comment by revolunet** [comment]
i can move the conf files to `/docker` but not the Dockerfile and docker-compose as they need the "context". good for you ?

**Comment by AntoineAugusti** [comment]
I'll need to update the docs accordingly after. The docs live in [this repository](https://github.com/entrepreneur-interet-general/bulletins-docs). You can submit a PR how explain how you would update the docs here and I'll change it myself.

**Comment by AntoineAugusti** [comment]
Sure, good for me

**Comment by revolunet** [comment]
done, moving on to the doc :)

**Comment by AntoineAugusti** [comment]
Related PR https://github.com/entrepreneur-interet-general/bulletins-docs/pull/3 and https://github.com/entrepreneur-interet-general/bulletins-docs/pull/4

**Comment by revolunet** [comment]
Yep i can access the app and view the history :)

**Comment by revolunet** [comment]
Capture d’écran 2019-10-18 à 12 19 27

**Comment by AntoineAugusti** [comment]
Thanks for the contribution @revolunet!

**Comment by AntoineAugusti** [comment]
Related PRs https://github.com/entrepreneur-interet-general/bulletins-docs/pull/3, https://github.com/entrepreneur-interet-general/bulletins-docs/pull/4

**Pull request merged**
